import "./assets/globals.css";
import Header from "./components/header";
// Local font tanımlamaya yarayan foknsiyon
import localFont from "next/font/local";

// Google Fonts'dan font çekme
import { Poppins } from "next/font/google";

// Local Fontlar
export const play = localFont({
  src: "./assets/fonts/PlaywriteCU-VariableFont_wght.ttf",
});

// Dış Kaynaktan Gelen Font Tanımlama
export const poppins = Poppins({
  weight: ["300", "400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Advanced",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // style={poppins.style}
        className={poppins.className}
      >
        <Header />

        {children}
      </body>
    </html>
  );
}
